plugin:
    name: 'MF Contacts View'
    description: 'Extends Magic Forms with custom backend handling'
    author: 'Kevin Ard'
    icon: oc-icon-envelope-o
    homepage: 'https://twitter.com/TheRealKevinArd'
