list: $/rwm/mfcontactsview/models/contacts/columns.yaml
modelClass: Rwm\MfContactsView\Models\Contacts
title: Contacts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rwm/mfcontactsview/contact/update/:id'
