title: Contacts
modelClass: Rwm\MfContactsView\Models\Contact
list: $/rwm/mfcontactsview/models/contact/columns.yaml
recordUrl: 'rwm/mfcontactsview/contacts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
