name: Contacts
form: $/rwm/mfcontactsview/models/contact/fields.yaml
modelClass: Rwm\MfContactsView\Models\Contact
defaultRedirect: rwm/mfcontactsview/contacts
create:
    redirect: 'rwm/mfcontactsview/contacts/update/:id'
    redirectClose: rwm/mfcontactsview/contacts
update:
    redirect: rwm/mfcontactsview/contacts
    redirectClose: rwm/mfcontactsview/contacts
